### ISSUE TITLE
How can I use a custom trained model on Deepstream?

### ISSUE THREAD

**Issue by nipunarora8** [thatbrguy/Deep-Stream-ONNX#17]
Hello, recently for my personal project, I trained a custom lightweight model and I am able to export model as pth, onnx and trt. 
I am not sure how to use that model with a deep stream pipeline for faster inference. Can you please suggest me some resources?

**Comment by thatbrguy** [comment]
Hi, it has been a while since I used deepstream. Hence, I am currently unsure of what resources to recommend for the task of using custom models with deepstream for faster inference. 

In this repository I have used a specific tiny yolo v2 onnx model with deepstream. I recommend you to research online for a more general guide on how to use an arbitrary onnx model with deepstream.
